### ISSUE TITLE
TypeError: prisma.item.cursorStream is not a function

### ISSUE THREAD

**Issue by erikstorli** [etabits/prisma-cursorstream#1]
This is **client.js** which I use around my project:

```
const prisma = require('@prisma/client');
prisma.Decimal.prototype.toJSON = function() {
    return this.toNumber();
}

const { PrismaClient } = prisma;
const cursorStream = require('prisma-cursorstream');

const prismaClient = new PrismaClient().$extends(cursorStream);

module.exports = prismaClient;
```

Then I initialize the client, and use it like this:
```
const prisma = require('../client');
const rows = prisma.item.cursorStream({
  select: {
    id: true
  }
});
```

But I just get `TypeError: prisma.item.cursorStream is not a function`. What am I doing wrong? findMany works. Using Prisma 5.6.0.

**Comment by aularon** [comment]
Hello @erikstorli! I believe this issue is because you are using the `require` syntax. In my usage I have only tested with `import`s. I will try to replicate the issue locally and see how I can fix exports to make your code work.

**Comment by aularon** [comment]
Hello again @erikstorli! It seems that in the require syntax you only need to make a slight modification:
```js
const cursorStream = require('prisma-cursorstream').default;
```
and it should work! Please test and let me know.

**Comment by erikstorli** [comment]
Works perfectly, and made the memory usage in the script much better than pagination. Thank you very much!

**Comment by aularon** [comment]
My pleasure! Happy to read about your experience, as it makes what I'm doing more meaningful.

I documented this in the README file, too. Thank you!

P.S. Do you mind if I use what you wrote as a testimonial in the documentation? Something along the lines of:
> Works perfectly, and made the memory usage in the script much better than pagination. — erikstorli

Best!

**Comment by erikstorli** [comment]
No problem at all 👍 Thank you again!
